# Introdução ao uso do módulo Numpy
---

In [1]:
# Por convenção a biblioteca numpy é exportada como se segue
import numpy as np

Numpy apresenta um tipo próprio de dado: `array numpy`. O array de python entendido com um vetor de objetos, tem sua funcionalidade ampliada dentro do Numpy.

In [2]:
dado = np.array([1,2,3,4])
matriz = np.array([[1,2,3,4],[5,6,7,8]])

type(dado), type(matriz)

(numpy.ndarray, numpy.ndarray)

In [3]:
# Imprime as dimenções do array
dado.shape, matriz.shape

((4,), (2, 4))

In [4]:
# Criancão de um array com n números ordenados np.arange(n)

x = np.arange(10)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

---
## Números Randômicos

Exemplos de funções para geração de arrays Numpy com números randômicos.

* `np.random.rand(n)`: gera um array com $n$ números aletórios entre 0 e 1;

* `np.random.randint(n,size=p)`: gera um array de tamanho $p$ com inteiros de $0$ até $n$;

* `np.random.rand(n,p)`: gera uma array de dimensões $n$ e $p$ com números aletórios.

In [5]:
x = np.random.rand(3)
y = np.random.randint(10,size=5)
z = np.random.rand(2,3)

x, y, z

(array([0.49379122, 0.83301222, 0.42471295]),
 array([6, 6, 7, 9, 0]),
 array([[0.29372808, 0.70568802, 0.38414232],
        [0.71160454, 0.59066898, 0.46655681]]))

In [6]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

---

## Arrays especiais

Exemplos de método para geração de arrays especiais

* `np.zeros((n,p))`: gera uma array de dimenções $n$ e $p$ com 0 (zeros), matriz composta de 0;

* `np.ones((n,p))`: gera uma array de dimenções $n$ e $p$ com 1;

* `np.empty((n,p))`: gera uma array de dimenções $n$ e $p$ com espaços vazios.

In [7]:
x = np.zeros((5,5))
y = np.ones((4,3))
z = np.empty((2,2))

x, y, z

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[4.67733425e-310, 0.00000000e+000],
        [3.16202013e-322, 0.00000000e+000]]))