# Matrizes em Numpy
---

In [1]:
import numpy as np

---

## Matriz diagonal

Uma matriz diagonal é uma matriz quadrada onde todos os elementos fora da diagonal principal são iguais a 0:
$$
D =\left[ \begin{matrix} 
d_{11} & 0 & 0 & \ldots & 0 \\
0 & d_{22} & 0 & \ldots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \ldots & d_{nn} \\
\end{matrix} \right]
$$

Com numpy uma matriz diagonal é criada usando o método:

* `np.diag((d1, d2, ... dn))`

Onde os números `d1, d2, ... dn` são  os `n` elementos da diagonal principal da matriz.


In [2]:
x = np.diag((1,-1,0,2))
x

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  2]])

---

## Matriz identidade

Matriz indentidade é uma matriz diagonal em que todos os elementos da diagonal principal são iguais a 1:
$$
I =\left[ \begin{matrix} 
1 & 0 & 0 & \ldots & 0 \\
0 & 1 & 0 & \ldots & 0 \\
\vdots & \vdots & \vdots  & \ddots & \vdots \\
0 & 0 & 0 & \ldots & 1 \\
\end{matrix} \right]
$$

Com numpy uma matriz identidade de ordem $n$ é criada usando o método:

* `np.eye(n)`

Em matemática usa-se a notação $I_n$ para uma matriz identidade de ordem $n$.

In [3]:
x = np.eye(4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

## Padrões de Matrizes

Usando o método `np.tile` é possível criar uma replicação de um array.

In [4]:
x = np.array([1,2])
x = np.tile(x,5)

y = np.array([[0,2],[1,3]])
y = np.tile(y,3)

x, y

(array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2]),
 array([[0, 2, 0, 2, 0, 2],
        [1, 3, 1, 3, 1, 3]]))

No método tile é possível usar também dois parâmetros de replicação.

In [5]:
x = np.array([1,2])
x = np.tile(x,(2,3))

y = np.array([[0,2],[1,3]])
y = np.tile(y,(4,3))

x, y

(array([[1, 2, 1, 2, 1, 2],
        [1, 2, 1, 2, 1, 2]]),
 array([[0, 2, 0, 2, 0, 2],
        [1, 3, 1, 3, 1, 3],
        [0, 2, 0, 2, 0, 2],
        [1, 3, 1, 3, 1, 3],
        [0, 2, 0, 2, 0, 2],
        [1, 3, 1, 3, 1, 3],
        [0, 2, 0, 2, 0, 2],
        [1, 3, 1, 3, 1, 3]]))

In [6]:
# O método tile pode ser usado para criar vetores ou matrizes com apenas um elemento

x = np.tile(np.array([5]),3)
y = np.tile(np.array([5]),(4,5))

x, y

(array([5, 5, 5]),
 array([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]))