# Atributos e Métodos 
---

In [1]:
import numpy as np

---

## `shape`

O atributo `shape` dos objetos do tipo array numpy, mostra a dimensão dos mesmos.

In [2]:
x = np.array([[1,2],[2,3],[-1,0]])
x, x.shape

(array([[ 1,  2],
        [ 2,  3],
        [-1,  0]]),
 (3, 2))

---

## `transpose`

O método `np.transpose()` faz a tranposição de um array numpy.

In [3]:
x, np.transpose(x)

(array([[ 1,  2],
        [ 2,  3],
        [-1,  0]]),
 array([[ 1,  2, -1],
        [ 2,  3,  0]]))

A transposta de uma array numpy também é um atributo do mesmo: `.T` 

In [4]:
x, x.T

(array([[ 1,  2],
        [ 2,  3],
        [-1,  0]]),
 array([[ 1,  2, -1],
        [ 2,  3,  0]]))

---

## `save`/`load`

Muitas vezes é necessário salvar um array numpy no disco. Isso é feito usando 

~~~
np.save('arrayx', x)
~~~

Assim o array numpy armazenado na variável `x`, será salvo na memória com o nome `arrayx.npy`.

In [5]:
np.save('matriz',x)

Quando um array está salvo no disco, a sua leitura e carregamento no código é feita com o método `load`. Fazendo

y = np.load('nome.npy')

Carregamos o array salvo no arquivo `nome.py` para a variável `y`.

In [6]:
y = np.load('matriz.npy')
y

array([[ 1,  2],
       [ 2,  3],
       [-1,  0]])