# Álgebra Linear com Python: Numpy
---

In [2]:
# Por convenção a biblioteca numpy é exportada como se segue
import numpy as np

---
## Básico da linguagem Python

In [3]:
# Imprimindo uma lista de números
for i in range(1,11):
    print(f'{i}, ', end="")

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

In [4]:
# Criando um dicionário
numeros = {}
numeros['um'] = 1
numeros['dois'] = 2
numeros.keys(), numeros.values()

(dict_keys(['um', 'dois']), dict_values([1, 2]))

In [5]:
numeros

{'um': 1, 'dois': 2}

In [6]:
x = ['um', 'dois']
y = [1,2]
d = {}

for i in range(len(x)):
    d[x[i]] = y[i]


In [7]:
d

{'um': 1, 'dois': 2}

---
## Usando a bibliote numpy

In [8]:
# Ciação de matrizes e vetores com Numpy
x = np.array([1,2,3])
y = np.array([[1,2,3],[1,1,1],[2,2,2]])

x,y


(array([1, 2, 3]),
 array([[1, 2, 3],
        [1, 1, 1],
        [2, 2, 2]]))

In [9]:
# Matriz diagonal
x = np.diag([1,2,3,4])

# Matriz nula
y = np.zeros(4)

x, y, np.transpose(x) # transposta de x 

(array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]),
 array([0., 0., 0., 0.]),
 array([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]))

In [10]:
# Matriz identidade
x = np.identity(4)
y = np.eye(4)

x,y

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

---

## Propriedades da Transposição de Matrizes

Dadas duas Matrizes $A$ e $B$, quadradas e de mesma ordem, temos

1. $(A+B)^T = A^T+B^T$;

1. $(A^T)^T = A$

1. $(\alpha A)^T = \alpha A^T$

In [11]:
# Verificação com Numpy
A = np.array([[1,2],[3,4]])
B = np.array([[0,0],[3,5]])

(A+B).T == A.T + B.T

array([[ True,  True],
       [ True,  True]])

---

## Propriedades do Traço de uma Matriz Quadrada

Dada uma matriz quadrada $A = [a_{ij}]$ de orde $n$, o traço de $A$, é dado por:

$$\mbox{tr}(A) =  a_{11} + a_{22} + \ldots + a_{nn},$$

soma dos elementos da diagonal principal. Dada outra matriz $B$, de ordem $n$ valem as seguintes propriedades:

1. $\mbox{tr}(A+B) = \mbox{tr}(A) + \mbox{tr}(B)$

2. $\mbox{tr}(\alpha A) = \alpha \mbox{tr}(A)$

3. $\mbox{tr}(A) = \mbox{tr}(A^T)$

4. $\mbox{tr}(AB) = \mbox{tr}(BA)$

5. O traço de uma matriz simétrica é a soma de seus auto valores.

In [12]:
# Testando uma das propriedades

np.trace(np.dot(A,B)) == np.trace(np.dot(B,A))

True

---

## Invertendo Matrizes

In [13]:
# Importando o método inv para inversão de matrizes do módulo linalg
# Linalg é o um conjunto de funcões python para algébra linear

# det, para calculo de determinantes
from numpy.linalg import inv,det

In [14]:
A, inv(A), det(A)

(array([[1, 2],
        [3, 4]]),
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 -2.0000000000000004)

In [15]:
A.dot(inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

---

## Resolução de Sistemas

Vamos resolver o sistema 
$$
\left\{
\begin{matrix}
2x + 3y & = & 2\\
4x - 5y & = & -40 
\end{matrix}
\right.
$$


In [16]:
from numpy.linalg import solve

In [17]:
A = np.array([[2,3],[4,-5]])
B = np.array([[2],[-40]])

A, B

(array([[ 2,  3],
        [ 4, -5]]),
 array([[  2],
        [-40]]))

In [18]:
solve(A,B)

array([[-5.],
       [ 4.]])

In [19]:
np.linalg.solve(A,B)

array([[-5.],
       [ 4.]])