# Autovalores e Autovetores
---

## Transformações Lineares

Dados dois espaços vetoriais $V$ e $W$, uma aplicação $P: V \rightarrow W$ é uma transformação linear de $V$ em $W$, se dados $u,v \in V$ e $\alpha \in \mathbb{R}^2$:

(i) $T(u+v) = T(u) + T(v)$;

(ii) $T(\alpha u) = \alpha T(u)$.

**Observações:** seja $V$ um espaço vetorial,

* uma transformação linear $ T: V \rightarrow V$ é chamada de operador linear;

* as transformações lineares $ T: V \rightarrow \mathbb{R}$ são chamadas de funcionais lineares.

* dados $v_1, v_2 \in V$ e $\alpha_1, \alpha_2 \in \mathbb{R}$, as duas propriedades (i) e (ii) de transformações lineares, podem ser sintetizadas na propriedade a seguir:

    (iii*) $T(\alpha_1 v_1 + \alpha_2 v_2) = \alpha_1 T(v_1) + \alpha_2 T(v_2)$

### Funções Lineares

Em matemática uma função $T: \mathbb{R} \rightarrow \mathbb{R}$ é chamada de linear se, dados $x,y, \alpha \in \mathbb{R}$:

* Aditividade
$$f(x+y) = f(x) + f(y)$$

* Homogeneidade
$$f(\alpha x) =  \alpha f(x)$$

## Matriz de uma Transformação Linear

Dados $V$ e $W$, espaços vetoriais, e seja a Transformação Linear $ T: V \rightarrow W$, existe uma matriz $A$, tal que, se para $v \in V$, temos $T(v) = w \in W$

$$
T(v) = Av = w 
$$

A matriz $A$ de uma transformação linear $ T: V \rightarrow W$ é dada por:
$$
A = \left[
\begin{matrix}
[T(i_1)] & [T(i_2)] & \ldots & [T(i_n)]
\end{matrix}
\right]
$$

Onde $i_1, i_2, \ldots , i_n$ são a base canônica de $V$. Assim cada uma das colunas da matriz da transformação linear é formada pela coordenadas do vetor resultado da transformação aplicada a um dos elementos da base canônica.


### Exemplos

#### Exemplo 1: Calcular a matriz da transformação linear $ T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ definida por:
$$
T(x,y) = (2x,3y,x-y)
$$


A base canônicas de $\mathbb{R}^2$ é composta pelos vetores $[1,0]$ e $[0,1]$, aplicando $T$ a cada um deles, obtemos $[2,0,1]$ e  $[0,3,-1]$, assim a matriz da tranformação linear é:
$$
A = \left[
\begin{matrix}
2 & 0\\
0 & 3\\
1 & -1
\end{matrix}
\right]
$$


In [1]:
# Vamos usar numpy para calcular T(1,1):
import numpy as np

In [2]:
A = np.array([[2,0],[0,3],[1,-1]])
A

array([[ 2,  0],
       [ 0,  3],
       [ 1, -1]])

In [3]:
v = np.array([[1],[1]])
v

array([[1],
       [1]])

In [4]:
np.dot(A,v)

array([[2],
       [3],
       [0]])

Na tranformação $T: \mathbb{R}^2 \rightarrow \mathbb{R}^3$ definida por $ T(x,y) = (2x,3y,x-y)$, obtemos uma matriz $A_{3 \times 2}$. Observe que o número de linhas da matriz é a dimensão do espaço vetorial $\mathbb{R}^3$ s o número de colunas é a dimensão do espaço vetorial $\mathbb{R}^2$.

Assim a $T(v) =  Av$, e podemos estudar as transformações lineares a partir de suas matrizes.

#### Exemplo 2: Calcular a matriz do operador linear $T(x,y) = (x-2y, 5x+6y)$. Use python para Calcular $T(50,-50)$

Calculando $T$ para $(1,0)$ e $(0,1)$, obtemos
$$
A = \left[
\begin{matrix}
1 & -2\\
5 & 6
\end{matrix}
\right]
$$

In [5]:
# Usando numpy para fazer T(50,-50)
A = np.array([[1,-2],[5,6]])
v = np.array([[50],[-50]])

A, v

(array([[ 1, -2],
        [ 5,  6]]),
 array([[ 50],
        [-50]]))

In [6]:
A.dot(v)

array([[150],
       [-50]])

## Composição de transformações lineares

As transformações lineares, assim como funções, podem ser compostas. No exemplo a seguir vamos ilustrar isso:

Seja os operadores lineares $T(x,y,z) = (2x - 5y, x + 4y - 2z, -y + 5z)$ e $P(x,y,z) = (2x, 3y, -7z)$, qual o resultado da operação $T(P(120,12,-13))$

A composição de duas transformações lineares gera uma segunda transformações linear. A matriz da transformações resultante é o produto das matrizes das transformações da composição. Assim para calcularmos usando python a operação pedida vamos encontrar as matrizes de cada uma das transformações lineares.

In [7]:
At = np.array([[2,-5,0],[1,4,-2],[0,-1,5]]) # matriz da transformação T
Ap = np.array([[2,0,0],[0,3,0],[0,0,-7]]) # matrix da transformação P

A = np.dot(At, Ap)  # matriz da composição
A

array([[  4, -15,   0],
       [  2,  12,  14],
       [  0,  -3, -35]])

In [8]:
v = np.array([[120],[12],[-13]])

In [9]:
A.dot(v)

array([[300],
       [202],
       [419]])

In [10]:
# Fazendo por partes
x = Ap.dot(v)
At.dot(x)

array([[300],
       [202],
       [419]])

## Inversa de uma transformação linear

Seja uma transformação linear $T: V \rightarrow W$, uma inversa à esquerda de $T$, é uma transformação $T^{-1}$, tal que:

$$
T^{-1}(T(v)) = v
$$

No caso dos operadores lineares, a matriz inversa da matriz dada é encontrada calculando a matriz inversa da matriz do operador linear, caso exista.

#### Exemplo 1: Calcule a inversa do operador linear $T(x,y) = (2x - 3y, 5x + 2y)$

In [11]:
from numpy.linalg import det, inv

In [12]:
A = np.array([[2,-3],[5,2]])
A, det(A)

(array([[ 2, -3],
        [ 5,  2]]),
 18.999999999999996)

In [13]:
inv(A)

array([[ 0.10526316,  0.15789474],
       [-0.26315789,  0.10526316]])

---
## Autovalores e Autovetores

É de interesse especial da álgebra linear os vetores que são levados em múltiplos de si mesmos por meio de um operador linear. 

Assim, dado um operador linear $T: V \rightarrow V$, cuja matriz é $A$ queremos encontrar um vetor $v \neq 0 \in V$ e um escalar $\lambda \in \mathbb{R}$, tais que: $T(v) = \lambda v$, ou seja

$$
Av = \lambda v
$$

O vetor $v$ é chamado de autovalor de $T$ ou da matriz $A$ e o escalar $\lambda$ é chamado de autovalor de $T$ ou da matriz $A$.

Os Autovalores de uma matriz $A$ podem ser encontrados como soluções da equação:
$$
\det(A-\lambda I) = 0
$$

O polinômio em $\lambda$, $p(\lambda) = \det(A-\lambda I)$ é chamado de polinômio característico da matriz $A$.

In [14]:
# Calculando autovalores e autovetores de uma matriz usando python
import numpy.linalg as al

In [15]:
A = np.array([[4,2,0],[-1,1,0],[0,1,2]])

autovalores, autovetores = al.eig(A)

autovalores, autovetores

(array([2., 2., 3.]),
 array([[ 0.00000000e+00,  4.44089210e-16, -8.16496581e-01],
        [ 0.00000000e+00, -4.44089210e-16,  4.08248290e-01],
        [ 1.00000000e+00,  1.00000000e+00,  4.08248290e-01]]))